# Dockerfile.test
FROM python:3.12-alpine

# Copier ton code
WORKDIR /app
COPY . /app

# Installer les dépendances de test
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest pytest-cov

CMD ["pytest", "-v", "-ra", "--tb=short", "--cov=app", "--cov-report=term-missing"]