services:
  compose_postgres_test:
    image: postgres:16.9-alpine
    container_name: compose_postgres_test_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    networks:
      - mon_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 3s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      compose_postgres_test:
        condition: service_healthy
    networks:
      - mon_network
    environment:
      DATABASE_URL: postgresql://test_user:test_password@compose_postgres_test:5432/test_db
      SECRET_KEY: "testsecret"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      PYTHONPATH: /app
networks:
  mon_network:
    driver: bridge
