# # Dockerfile.test
# FROM restausimplon_api_image

# # Installer pytest et faker si besoin
# #on repasse en root
# USER root
# RUN pip install pytest pytest-cov pytest-clarity

# #on revient sur l'utilisateur normal par sécurité
# USER restausimplon-app-user

# # Copier le code + tests
# COPY ./tests ./tests

# ENV PYTHONPATH=/app

# # Commande par défaut
# # CMD ["pytest", "-v"]
# CMD ["pytest", "-v", "-ra", "--tb=short", "--cov=app", "--cov-report=term-missing"]

# Dockerfile.test
FROM python:3.12-alpine

# Copier ton code
WORKDIR /app
COPY . /app

# Installer les dépendances de test
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest

CMD ["pytest", "-v", "-ra", "--tb=short", "--cov=app", "--cov-report=term-missing"]