name: CI

on:
  push:
    branches: ["develop"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov coverage

      - name: Debug environment
        env:
          DATABASE_URL: sqlite:///:memory:
        run: |
          echo "DATABASE_URL=$DATABASE_URL"
          python -m pip show coverage || echo "coverage NOT installed"
          python -m pip show pytest-cov || echo "pytest-cov NOT installed"
          python -m pip show pytest || echo "pytest NOT installed"

      - name: Run tests with coverage
        env:
          SECRET_KEY: test_secret_key
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: "15"
          REFRESH_TOKEN_EXPIRE_DAYS: "7"
          DATABASE_URL: sqlite:///:memory:
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to GitHub summary
        if: success()
        run: |
          echo "### Coverage Report" >> $GITHUB_STEP_SUMMARY
          coverage report -m >> $GITHUB_STEP_SUMMARY
